version: '3'

services:

    jedi-consumer:
        build: ./jedi-masters-consumer/
        command: npm start
        working_dir: /jedi-masters-consumer
        volumes:
          - .:/jedi-masters-consumer
        ports:
          - 3001:3001
        restart: on-failure
        depends_on:
          - postgresql
          - rabbitmq
        environment:
          AMQP_URL: amqp://localhost:15672
    postgresql:
        image: postgres:9.6.2-alpine
        ports:
          - 5432:5432
    rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 15672:15672
          - 15671:15671
          - 5672:5672
    jedi-producer:
        build: ./jedi-masters-producer/
        command: npm start
        working_dir: /jedi-masters-producer
        volumes:
          - .:/jedi-masters-producer
        ports:
          - 3002:3002
        restart: on-failure
        depends_on:
          - rabbitmq
        environment:
          AMQP_URL: amqp://localhost:15672