version: '2'

services:
    jedi-masters-consumer:
         build: ./jedi-masters-consumer
         ports:
            - "3001:3001"

    jedi-masters-producer:
         build: ./jedi-masters-producer
         ports:
            - "3002:3002"



    postgresql:
        image: postgres:9.6.2-alpine
        ports:
          - 5432:5432
    rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 15672:15672
          - 15671:15671
          - 5672:5672