version: '2'

services:
    db:
        image: postgres:9.6.2-alpine
        ports:
          - 5433:5432
    queue:
        image: rabbitmq:3-management
        ports:
          - 15672:15672
          - 15671:15671
          - 5672:5672
    jedi-masters-consumer:
         build: .
         command: npm run start
         image: matys/consumer
         ports:
            - "3001:3001"
         volumes:
            - .:/app
         depends_on:
            - db
            - queue